app1/urls.py
from django.conf.urls import url

from . import views

app_name = 'app1'
urlpatterns = [
#    url(r'^$', views.index, name='index'),
    url(r'^$', views.home, name='index'),

    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^i/(?P<picture_id>[0-9]+)/$', views.picture, name='picture'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^picupload/$', views.picupload, name='picupload'),
    url(r'^home/$', views.home, name='home'),
    url(r'^search_result/$', views.search_result, name='search_result'),
    url(r'^tag_list/$', views.tag_list, name='tag_list'),
    url(r'^api/api_get_picture_tags/$', views.api_get_picture_tags, name='api_get_picture_tags'),
    url(r'^api/api_remove_tag_from_picture/$', views.api_remove_tag_from_picture, name='api_remove_tag_from_picture'),
    url(r'^api/api_get_picture_tags_with_term/$', views.api_get_picture_tags_with_term, name='api_get_picture_tags_with_term'),
    url(r'^api/api_get_picture_tags_with_term_1/$', views.api_get_picture_tags_with_term_1, name='api_get_picture_tags_with_term_1'),
    url(r'^api/api_update_picture_tags/$', views.api_update_picture_tags, name='api_update_picture_tags'),
]

p1/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^app1/', include('app1.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

#
# Let's create my own classes
#
#

class PictureTag(models.Model):
    text = models.TextField(max_length=256)

    def __str__(self):
        return self.text


class Picture(models.Model):
    pict = models.ImageField(upload_to='pictures')
    tags = models.ManyToManyField(PictureTag, blank=True)
    upload_date = models.DateTimeField('date uploaded')

    def __str__(self):
        return self.pict.name

app1/views.py
import json
from django.shortcuts import get_object_or_404, render

# Create your views here.
from django.http import Http404
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.urls import reverse

from django import forms
from django.utils import timezone


from .models import Choice, Question, Picture, PictureTag

from django.core import serializers

# Index page
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#    output = ', '.join([q.question_text for q in latest_question_list])
#    return HttpResponse(output)

    template = loader.get_template('app1/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))


# Detail page
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")

    return render(request, "app1/detail.html", {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'app1/results.html', {'question': question})



def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'app1/detail.html', {'question':question, 'error_message':"You din't select a choice."},)
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('app1:results', args=(question.id,)))



# image upload form
class ImageUploadForm(forms.Form):
    image = forms.ImageField()


def picture_create_tags(picture, tags_text):
    if tags_text == "": return

    tags = tags_text.strip().replace(' ', '_').split(',') # all space will be replaced to '_'
    for t in tags:
        picture_tag, created = PictureTag.objects.get_or_create(text=t.strip())
        picture.tags.add(picture_tag)

    return


def picupload(request):
    saved = False
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            m = Picture()
            m.pict = form.cleaned_data['image']
            m.upload_date = timezone.now()
            m.save()
            picture_create_tags(m, request.POST.get('tags'))
            saved = True

#    return render(request, 'app1/uploadcompleted.html', locals())
    return render(request, 'app1/picture.html', {'picture':m})


def upload(request):
    return render(request, 'app1/upload.html')


def gallery(request):
    latest_picture_list = Picture.objects.order_by('-upload_date')[:10]

    return render(request, 'app1/gallery.html', {'pictures':latest_picture_list})


def picture(request, picture_id):
    picObj = get_object_or_404(Picture, pk=picture_id)
    return render(request, 'app1/picture.html', {'picture':picObj})

def home(request):
    return render(request, 'app1/home.html')


def tag_list(request):
    tags = PictureTag.objects.all()
    return render(request, 'app1/tag_list.html', {'tags': tags})


def search_result_find_id(pictures, id):
    for i in pictures:
        if id == i['id']: return True
    return False


def search_result(request):
    query_text = request.GET.get('q')
    query_text_w_space = query_text.replace(',', ' ')
    queries = query_text.split(',')
    pictures = []

    for q in queries:
        searched_picture_list = Picture.objects.filter(tags__text=q)
        for p in searched_picture_list:
            d = {'url': p.pict.url, 'id': p.id}
            if not search_result_find_id(pictures, p.id):
                 pictures.append(d)

    return render(request, 'app1/search_result.html', {'query_text':query_text_w_space, 'pictures':pictures})


# picture_id is required as one of GET parameter
# return the serialized JSON text for array of PictureTag model-object
def api_get_picture_tags(request):
    picture_id = request.GET.get('picture_id')
    if picture_id:
        picObj = get_object_or_404(Picture, pk=picture_id)
        tags = picObj.tags.all()
        text = serializers.serialize('json', tags)

    return HttpResponse(text)

# picture_id is required as one of GET parameter
# tag_id is for removing from the picture associated with picture_id
# return the serialized JSON text for array of PictureTag model-object
def api_remove_tag_from_picture(request):
    picture_id = request.GET.get('picture_id')
    tag_id = request.GET.get('tag_id')
    if picture_id and tag_id:
        picObj = get_object_or_404(Picture, pk=picture_id)
        tags = picObj.tags.filter(pk=tag_id)
        if len(tags) > 0:
            picObj.tags.remove(tags[0])

        picObj.tags.all()
        text = serializers.serialize('json', tags)

    return HttpResponse(text)


# 'picture_id' is required as one of GET parameter
# 'tags' which has coma separated text for picture tag is also required as GET parameter
# return the serialized JSON text for array of PictureTag model-object
def api_update_picture_tags(request):
    picture_id = request.GET.get('picture_id')
    tag_text = request.GET.get('tags')
    result = 0
    if picture_id and tag_text:
        m = get_object_or_404(Picture, pk=picture_id)
        picture_create_tags(m, tag_text)
        result = 1

    return HttpResponse(result)

# Helper function for autocomplete key APIs
#
# maxCandidate means that the max number of key which is the filter results
#
# If isMulti is True, space-separated query is treated as separete keywords.
#   in this case, client code (i.e. JQuery programe) needs to handle multi query as well.
#
def helpter_api_get_picture_tags_with_term(request, isMulti, maxCandidate):
    if request.is_ajax():
        q = request.GET.get('term', '')

        if isMulti:
            # jquery sends 'something somthing2 XXX ...' if input box has separate text with 'space'
            # Hence, I'll try to get last text for searching in database!
            q2 = q.split(' ')[-1]
        else:
            q2 = q

        #        print("here!: " + q2)

        # making query for db
        tags = PictureTag.objects.filter(text__contains=q2)[:maxCandidate]
        results = []
        for tag in tags:
            tag_json = {}
            tag_json['id'] = tag.id
            tag_json['label'] = tag.text
            tag_json['value'] = tag.text
            results.append(tag_json)
        data = json.dumps(results)
    else:
        data = 'fail'

    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

# single version of api_get_picture_tags_with_term
def api_get_picture_tags_with_term_1(request):
    return helpter_api_get_picture_tags_with_term(request, False, 10)

# 'term' is what Jquery adds for autocomplete key
# return the serialized JSON text for autocomplete array of 'source' object
def api_get_picture_tags_with_term(request):
    return helpter_api_get_picture_tags_with_term(request, True, 15)

app1/templates/app1/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>

<h1>{{ question }}</h1>
<!--
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul>
-->

<form action="{% url 'app1:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />

</form>

</body>
</html>

app1/templates/app1/gallery.html
<!DOCTYPE html>

{% load static %}
<html lang="en">


<head>
<meta charset="UTF-8">

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'image-picker/image-picker.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'image-picker/image-picker.css' %}">
<style type="text/css">.thumbnails li img {width: 180px;} </style>

<link rel="stylesheet" href="{% static 'bootstrap/3.3.6/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap/3.3.6/css/bootstrap-theme.min.css' %}">
<script src="{% static 'bootstrap/3.3.6/js/bootstrap.min.js' %}"></script>


<link rel="stylesheet" href="{% static 'ymenubar.css' %}">

    <meta charset="UTF-8">
    <title>Recent uploaded</title>

</head>


<body>
<!-- menu bar -->

<ul class="ymenubar">
  <li><a href="{% url 'app1:home' %}">Home</a></li>
  <li><a class="active" href="{% url 'app1:gallery' %}">Gallery</a></li>
  <li><a href="{% url 'app1:tag_list' %}">Tag list</a></li>
  <li><a href="{% url 'app1:upload' %}" >Upload</a></li>
  <li><a href="#This">Picture</a></li>
</ul>

<!-- contents boady -->
<div class="container">
    <h2> Recent uploaded images </h2>
    <div class="picker">
        <select class="pk show-html">
            {% if pictures %}
                {% for obj in pictures %}
                    <option data-img-src="{{ obj.pict.url }}" value="{{ forloop.counter }}" page="{% url 'app1:picture' obj.id %}"> {{ forloop.counter }} </option>
                {% endfor %}
            </ul>
            {% endif %}
        </select>
    </div>
</div>
</body>
<script type="text/javascript">
    $("select.pk").imagepicker({hide_select: true,
    clicked: function() {
        var a = $(this).find("option[value='" + $(this).val() + "']");
        window.location = a.attr('page');
    }});
</script>
</html>

app1/templates/app1/home.html
<!DOCTYPE html>

{% load static %}
<html lang="en">

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

<link rel="stylesheet" href="{% static 'bootstrap/3.3.6/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap/3.3.6/css/bootstrap-theme.min.css' %}">
<script src="{% static 'bootstrap/3.3.6/js/bootstrap.min.js' %}"></script>

<link rel="stylesheet" href="{% static 'ymenubar.css' %}">

<head>
    <meta charset="UTF-8">
    <title>Picture</title>
</head>
<body>

<!-- menu bar -->

<ul class="ymenubar">
  <li><a class="active" href="{% url 'app1:home' %}">Home</a></li>
  <li><a href="{% url 'app1:gallery' %}">Gallery</a></li>
  <li><a href="{% url 'app1:tag_list' %}">Tag list</a></li>
  <li><a href="{% url 'app1:upload' %}" >Upload</a></li>
  <li><a href="#This">Picture</a></li>
</ul>

<!-- contents body -->

<div class="container">
    <center>
        <p><h2>Search picture with kewords</h2>

        <!--
        <form class="form-inline" action="{% url 'app1:search_result' %}" method="get">{% csrf_token %}
            <input type="text" name="q">
            <input type="submit" value="Search" class="btn btn-success" />
        </form>
        -->
        <input type="text" id="q" />
        <input type="button" value="Search" class="btn btn-success btn-search" />
        <br>
    </center>

    <!-- for debug -->
    <div class="dbg"></div>

    <script type="text/javascript">

    // for debuging
    function D(txt) {
        o = $('div.dbg').html();
        $('div.dbg').html(o + "<br>" +txt);
    };

    $("input.btn-search").click(function() {
        var org = $("#q").val();
        var s1 = org.split(" ");
        window.location = "{% url 'app1:search_result' %}" + "?q=" + s1;
    });

    $("#q").autocomplete({
        source: "{% url 'app1:api_get_picture_tags_with_term' %}",
        multiple: true,
        multipleSeparator: " ",
        select: function(e, ui) {return false;}, // disabling default impl.
        focus: function(e, ui) {
            var t = this.value.split(' ');
            t.pop();
            t.push(ui.item.value);
            this.value = t.join(' ');
            return false;
        },
    });

    $("#q").keyup(function(e) {
        if (e.keyCode == 13) {
            $("input.btn-search").click();
        }
    });
    $("#q").focus();
    </script>

</div>
</body>
</html>

app1/templates/app1/picture.html
<!DOCTYPE html>

{% load static %}
<html lang="en">

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

<link rel="stylesheet" href="{% static 'bootstrap/3.3.6/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap/3.3.6/css/bootstrap-theme.min.css' %}">
<script src="{% static 'bootstrap/3.3.6/js/bootstrap.min.js' %}"></script>

<link rel="stylesheet" href="{% static 'ymenubar.css' %}">

<style type="text/css">
    .ui-droppable-hover {
        border: 1px;
        border-color: grey;
        border-style: solid;
    }
    .trash-image {
        margin-left: 80px;
        display:inline-block;
        width:32px;
        height:32px;
        background-image: url('{% static 'trash-icon.png' %}');
    }
</style>

<head>
    <meta charset="UTF-8">
    <title>Picture</title>
</head>
<body>

<!-- menu bar -->

<ul class="ymenubar">
  <li><a href="{% url 'app1:home' %}">Home</a></li>
  <li><a href="{% url 'app1:gallery' %}">Gallery</a></li>
  <li><a href="{% url 'app1:tag_list' %}">Tag list</a></li>
  <li><a href="{% url 'app1:upload' %}" >Upload</a></li>
  <li><a class="active" href="#This">Picture</a></li>
</ul>

<!-- contents body -->

<div class="container">

    <center>
        <h2>{{ picture.pict.name }} </h2>

        <img src="{{ picture.pict.url}}" style="max-width: 480px;" />
        <p></p>
    </center>


    <table class="table">
        <tr>
            <td>Uploaded date : </td><td align="left">{{ picture.upload_date }}</td>
        </tr>
        <tr>
            <td>Tags :</td>
            <td class="tag_btn_place"></td>
        </tr>
        <tr>
            <td>Add new tags :</td>
            <td><input type="text" class="new_tag_text"/><input class="new_tag_btn btn-success btn-sm" type="button" value="Add"/></td>
        </tr>
        <tr>
        </tr>
    </table>

    <div id="remove_tag_dialog" title="Info:">
        Do you want to remove the tag from this picture?<br>
        <h4><div id="remove_tag_dialog_text"></div></h4>
    </div>
</div>

<script type="text/javascript">
    // Throw the ajax request to get all tag associated with this page 'picture' id
    // picture.id comes from the server thru the django template
    function picture_html_update_tag_btn() {
        tag_btn_place = $("td.tag_btn_place");
        $('div').remove(".badge");
        $('div').remove(".trash-image");
        $('div').remove(".noavailable");

        // $.now() is to avoid browser caching the request... (e.g. MS Edge)
        $.get('{% url 'app1:api_get_picture_tags' %}', {picture_id:{{ picture.id }}, "_": $.now() }, function(data) {
            obj = $.parseJSON(data);
            for (i = 0; i < obj.length; i++) {
                obj_input_text = "<div style='margin-right:4px' class='badge btn'>" + obj[i].fields.text + "</div>"
                a = $(obj_input_text).appendTo(tag_btn_place).hide().fadeIn(800);
//                a = $(obj_input_text).appendTo(tag_btn_place);
                a.data('tag_id', obj[i].pk);
                a.click(function() {
                    if ($(this).hasClass('noclick')) {
                        $(this).removeClass('noclick');
                    } else {
                        window.location = "{% url 'app1:search_result' %}"+ "?q=" + $(this).html();
                    }
                });
                a.draggable( {distance:10, revert:true, cursor: 'move',
                    start: function(e,u){$(this).addClass('noclick');}
                });
            }

            // Let's show text if no tag is available..
            if (obj.length <= 0) {
                obj_no_available = "<div class='noavailable'> not available</div>";
                $(obj_no_available).appendTo(tag_btn_place).fadeIn(8000);
            }
            // otherwise, show trash icon to let user remove tas
            else {
                obj_trash = "<div class='trash-image'></div>";
                $(obj_trash).appendTo(tag_btn_place).droppable( {
                    drop: function(e,u) {
//                        alert('draggable tag_id =' + u.draggable.data('tag_id') + ':' + u.draggable.html());
                        $("#remove_tag_dialog_text").html("'" + u.draggable.html() + "'");
                        $("#remove_tag_dialog").data('draggable', u.draggable).dialog("open");
                    }
                } );
                $(obj_trash).tooltip( {
                    content: "Drag and drop the tag here to remove it from the picture"
                });
            }

            $("input.new_tag_text").val("").focus();
        });
    }

    // update 'tag' badges as page initialing process
    $(document).ready(function() {
        picture_html_update_tag_btn();
    });

    // when user clicks on the add new tags button, this function is called
    // it makes request to the server to add new tags which is typed in text box to the associated picture object
    $("input.new_tag_btn").click(function() {
        tag_text = $('input.new_tag_text').val();
        if (tag_text == "") return;

        $.get('{% url 'app1:api_update_picture_tags' %}', {picture_id:{{ picture.id }}, tags:tag_text}, function(data) {
            if (data == 1)
                window.setTimeout(function() {picture_html_update_tag_btn();}, 10);
            else
                alert('can not connect to the server or internal error occurred.');
        });
    });

    // when user press 'Enter' key on the keyboard, this function is called with keyCode==13
    // it should be equivalent to the button click()
    $("input.new_tag_text").keyup(function(e) {
        if (e.keyCode == 13) {
            $("input.new_tag_btn").click();
        }
    });

    // autocomplete function for tags
    // it would help user input the tag which is already stored in db.
    $("input.new_tag_text").autocomplete({
        source: "{% url 'app1:api_get_picture_tags_with_term_1' %}",
    });

    // remove tag
    $("#remove_tag_dialog").dialog({ autoOpen: false, modal: true,
        buttons: {
            Yes: function() {
                var tag_id_to_remove = $(this).data('draggable').data('tag_id');
                $.get('{% url 'app1:api_remove_tag_from_picture' %}', {picture_id:{{ picture.id }}, tag_id: tag_id_to_remove },
                    function(data) {
                        picture_html_update_tag_btn();
                    }
                );

                // finally, dialog will be going to close!
                $(this).dialog("close");
            },
            No: function() { $(this).dialog("close");}
        }
    });

    // the 'Add new tags' input wants to get the focus as page initial stage...
    $("input.new_tag_text").focus();
</script>

</body>

</html>

app1/templates/app1/search_result.html
<!DOCTYPE html>
{% load static %}
<html lang="en">


<head>
    <meta charset="UTF-8">
<!-- image picker -->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

<script type="text/javascript" src="{% static 'image-picker/image-picker.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'image-picker/image-picker.css' %}">
<style type="text/css">.thumbnails li img {width: 180px;} </style>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="{% static 'bootstrap/3.3.6/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap/3.3.6/css/bootstrap-theme.min.css' %}">
<script src="{% static 'bootstrap/3.3.6/js/bootstrap.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'ymenubar.css' %}">

    <title>Upload your picture</title>
</head>
<body>

<!-- menu bar -->

<ul class="ymenubar">
  <li><a class="active" href="{% url 'app1:home' %}">Home</a></li>
  <li><a href="{% url 'app1:gallery' %}">Gallery</a></li>
  <li><a href="{% url 'app1:tag_list' %}">Tag list</a></li>
  <li><a href="{% url 'app1:upload' %}" >Upload</a></li>
  <li><a href="#This">Picture</a></li>
</ul>

<!-- contents body -->
<p>

</p>
<div class="container">
    <input type="text" id="q" />
    <input type="button" value="Search" class="btn btn-success btn-search" />
</div>

<p>

</p>


<!-- pictures -->

<div class="container">
    <div class="picker">
        <select class="pk show-html">
            {% for p in pictures %}
                <option data-img-src="{{ p.url }}" value="{{ forloop.counter }}" page="{% url 'app1:picture' p.id %}"> {{ forloop.counter }} </option>
            {% endfor %}
        </select>
    </div>
    {% if pictures|length == 0 %}
        <h4> </h4>
        <div class="alert alert-warning">
            not match.
        </div>
    {% endif %}
</div>

</body>

<script type="text/javascript">
    $("select.pk").imagepicker({hide_select: true,
    clicked: function() {
        var a = $(this).find("option[value='" + $(this).val() + "']");
        window.location = a.attr('page');
    }});

    $("input.btn-search").click(function() {
        var org = $("#q").val();
        var s1 = org.split(" ");
        window.location = "{% url 'app1:search_result' %}" + "?q=" + s1;
    });

    $("#q").autocomplete({
        source: "{% url 'app1:api_get_picture_tags_with_term' %}",
        multiple: true,
        multipleSeparator: " ",
        select: function(e, ui) {return false;}, // disabling default impl.
        focus: function(e, ui) {
            var t = this.value.split(' ');
            t.pop();
            t.push(ui.item.value);
            this.value = t.join(' ');
            return false;
        },
    });

    $("#q").keyup(function(e) {
        if (e.keyCode == 13) {
            $("input.btn-search").click();
        }
    });
    $("#q").focus().val("").val("{{ query_text }}");
</script>

</html>

app1/templates/app1/tag_list.html
<!DOCTYPE html>

{% load static %}
<html lang="en">

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'bootstrap/3.3.6/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap/3.3.6/css/bootstrap-theme.min.css' %}">
<script src="{% static 'bootstrap/3.3.6/js/bootstrap.min.js' %}"></script>

<link rel="stylesheet" href="{% static 'ymenubar.css' %}">

<head>
    <meta charset="UTF-8">
    <title>Picture tag list</title>
</head>
<body>

<!-- menu bar -->

<ul class="ymenubar">
  <li><a href="{% url 'app1:home' %}">Home</a></li>
  <li><a href="{% url 'app1:gallery' %}">Gallery</a></li>
  <li><a class="active" href="{% url 'app1:tag_list' %}">Tag list</a></li>
  <li><a href="{% url 'app1:upload' %}" >Upload</a></li>
  <li><a href="#This">Picture</a></li>
</ul>

<!-- contents body -->
<div class="container">
    <h2> 'tag' associated with pictures</h2>

    <table class="table table-striped">
        {% for t in tags %}
        <tr>
            <td><div class='badge btn'>{{ t.text }}</div></td>
        </tr>
        {% endfor %}
    </table>
</div>


</body>

<script type="text/javascript">
    $('div.badge').click(function() {
        window.location = "{% url 'app1:search_result' %}"+ "?q=" + $(this).html();
    });
</script>

</html>

app1/templates/app1/upload.html
<!DOCTYPE html>
{% load static %}
<html lang="en">


<head>
    <meta charset="UTF-8">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="{% static 'bootstrap/3.3.6/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap/3.3.6/css/bootstrap-theme.min.css' %}">
<script src="{% static 'bootstrap/3.3.6/js/bootstrap.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'ymenubar.css' %}">

    <title>Upload your picture</title>
</head>
<body>

<!-- menu bar -->

<ul class="ymenubar">
  <li><a href="{% url 'app1:home' %}">Home</a></li>
  <li><a href="{% url 'app1:gallery' %}">Gallery</a></li>
  <li><a href="{% url 'app1:tag_list' %}">Tag list</a></li>
  <li><a class="active" href="{% url 'app1:upload' %}" >Upload</a></li>
  <li><a href="#This">Picture</a></li>
</ul>

<!-- contents body -->
<div class="container">
    <h1> Upload file ...</h1>
    <div class="container">
        <form class="form-inline" action="{% url 'app1:picupload' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
            <input id="id_image" type="file" name="image" class="filestyle">
            Tags:<input type="text" name="tags">
            <input type="submit" value="Submit" class="btn btn-primary" />
        </form>
    </div>
</div>


</body>
</html>